apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cel6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cel6
    app.kubernetes.io/part-of: ci10t-776-0083-app
  name: devfile-sample-cel6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cel6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cel6
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0083-tenant/ci10t-776-0083-app/devfile-sample-cel6@sha256:d852a30c5e9b39101c355cff7a66f56bf75356964c4a042fc06b3e0279528553
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
